services:
  
  backend:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_started
    links:
      - "database:database"
    volumes:
      - 'front_build:/var/www/html/'
  
  phpmyadmin:
    image: phpmyadmin
    profiles: [dev]
    ports:
      - 4242:80
    environment:
      - PMA_HOST=172.21.82.208
      - PMA_PORT=3306
      - PMA_USER=Group3
      - PMA_PASSWORD=6067
      # - PMA_CONTROLUSER=human
      # - PMA_CONTROLPASS=the_cake_is_a_lie
      - PMA_PMADB=Group3
    depends_on:
      database:
        condition: service_started
    links:
      - "database:database"
  
  website:
    build:
      context: ./Website
      dockerfile: ./Dockerfile
#      args:
#        HOST: "0.0.0.0"
#        PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - 'front_build:/html/'
  
  database:
    image: mariadb
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - "db:/var/lib/mysql"
      - "./Database/init.sql:/docker-entrypoint-initdb.d/1.sql"

volumes:
  db:
    driver: local
  front_build:
    driver: local